# Generated by Django 4.2.25 on 2025-11-10 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_trabajo', models.TextField()),
                ('fecha_servicio', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('proceso', 'En proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='vehiculo.vehiculo')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'vehiculo_servicio',
                'ordering': ['-fecha_servicio'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('boleta', 'Boleta'), ('certificado', 'Certificado'), ('presupuesto', 'Presupuesto'), ('informe', 'Informe técnico'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('fecha_documento', models.DateField()),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/%d/')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='servicios.servicio')),
            ],
            options={
                'ordering': ['-fecha_documento'],
            },
        ),
    ]
