# Generated by Django 4.2.25 on 2025-11-10 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='servicios/fotos/%Y/%m/%d/')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='servicios.servicio')),
            ],
            options={
                'verbose_name': 'Foto de Servicio',
                'verbose_name_plural': 'Fotos de Servicios',
                'ordering': ['-fecha_captura'],
            },
        ),
    ]
