# Generated by Django 5.2.5 on 2025-11-04 21:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, default='Servicios', max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nombre', models.CharField(blank=True, max_length=200)),
                ('empresa_rut', models.CharField(blank=True, max_length=20)),
                ('empresa_giro', models.CharField(blank=True, max_length=200)),
                ('empresa_direccion', models.TextField(blank=True)),
                ('empresa_telefono', models.CharField(blank=True, max_length=20)),
                ('empresa_email', models.EmailField(blank=True, max_length=254)),
                ('numero_cotizacion', models.CharField(blank=True, max_length=20, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now)),
                ('fecha_validez', models.DateField(blank=True, null=True)),
                ('forma_pago', models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otro', 'Otro')], max_length=20)),
                ('plazo_pago', models.CharField(blank=True, choices=[('contado', 'Al Contado'), ('15', '15 días'), ('30', '30 días'), ('45', '45 días'), ('60', '60 días'), ('90', '90 días')], max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado_cotizacion', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente')),
            ],
        ),
    ]
