# Generated by Django 4.2.24 on 2025-10-31 20:06

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='empresa_direccion',
            field=models.TextField(blank=True, default='Av. Principal 123, Osorno, Chile'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='empresa_email',
            field=models.EmailField(blank=True, default='contacto@tallermecanico.cl', max_length=254),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='empresa_giro',
            field=models.CharField(blank=True, default='Servicios de Mecánica Automotriz', max_length=200),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='empresa_nombre',
            field=models.CharField(blank=True, default='Taller Mecánico Rápido', max_length=200),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='empresa_rut',
            field=models.CharField(blank=True, default='76.123.456-7', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='empresa_telefono',
            field=models.CharField(blank=True, default='+56 9 1234 5678', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_validez',
            field=models.DateField(default=datetime.date(2025, 10, 31)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='plazo_pago',
            field=models.CharField(blank=True, choices=[('contado', 'Al Contado'), ('15', '15 días'), ('30', '30 días'), ('45', '45 días'), ('60', '60 días'), ('90', '90 días')], max_length=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada del trabajo a realizar'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(default='Servicios', max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizacion')),
            ],
        ),
    ]
