# Generated by Django 4.2.24 on 2025-11-11 04:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_fotoservicio'),
        ('clientes', '0001_initial'),
        ('cotizaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='itemcotizacion',
            options={'ordering': ['id'], 'verbose_name': 'Item de cotización', 'verbose_name_plural': 'Items de cotización'},
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última modificación'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cotizaciones/logos/', verbose_name='Logo de la empresa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_direccion',
            field=models.TextField(blank=True, verbose_name='Dirección de la empresa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de la empresa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_giro',
            field=models.CharField(blank=True, max_length=200, verbose_name='Giro de la empresa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre de la empresa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_rut',
            field=models.CharField(blank=True, max_length=20, verbose_name='RUT de la empresa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono de la empresa'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_validez',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de validez'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otro', 'Otro')], max_length=20, verbose_name='Forma de pago'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='IVA (19%)'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto total'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de cotización'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='plazo_pago',
            field=models.CharField(blank=True, choices=[('contado', 'Al Contado'), ('15', '15 días'), ('30', '30 días'), ('45', '45 días'), ('60', '60 días'), ('90', '90 días')], max_length=10, verbose_name='Plazo de pago'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='servicios.servicio', verbose_name='Servicio relacionado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='categoria',
            field=models.CharField(blank=True, default='Servicios', max_length=100, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizacion', verbose_name='Cotización'),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio unitario'),
        ),
    ]
