# Generated by Django 4.2.24 on 2025-10-31 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_cotizacion_empresa_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='vehiculo',
        ),
    ]
