# Generated by Django 4.2.24 on 2025-11-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0002_alter_cotizacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='empresa_contacto_persona',
            field=models.CharField(blank=True, max_length=100, verbose_name='Persona de contacto'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='empresa_sitio_web',
            field=models.URLField(blank=True, null=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='notas_adicionales',
            field=models.TextField(blank=True, help_text='Observaciones, términos o condiciones especiales', verbose_name='Notas adicionales'),
        ),
    ]
