# Generated by Django 4.2.24 on 2025-11-01 05:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_contacto_cliente_email_alter_cliente_rut_and_more'),
        ('cotizaciones', '0003_remove_cotizacion_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Descripción detallada del trabajo a realizar'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_validez',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='categoria',
            field=models.CharField(blank=True, default='Servicios', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
