# Generated by Django 5.2.5 on 2025-11-22 19:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_activo_cliente_fecha_eliminacion'),
        ('cotizaciones', '0003_cotizacion_empresa_contacto_persona_and_more'),
        ('servicios', '0002_fotoservicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='itemcotizacion',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_contacto_persona',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_giro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_rut',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_sitio_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado_cotizacion',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_validez',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otro', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='cotizaciones/logos/'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='monto_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='notas_adicionales',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='plazo_pago',
            field=models.CharField(blank=True, choices=[('contado', 'Al Contado'), ('15', '15 días'), ('30', '30 días'), ('45', '45 días'), ('60', '60 días'), ('90', '90 días')], max_length=10),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='categoria',
            field=models.CharField(blank=True, default='Servicios', max_length=100),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizaciones.cotizacion'),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='itemcotizacion',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
