# Generated by Django 4.2.24 on 2025-11-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_alter_cotizacion_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cotizacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cotizacion',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_rut',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
