# Generated by Django 4.2.24 on 2025-11-23 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_alter_itemcotizacion_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
