# Generated by Django 4.2.24 on 2025-11-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0005_remove_cotizacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_direccion',
            field=models.TextField(blank=True, default='Av. Principal 123, Osorno, Chile'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_email',
            field=models.EmailField(blank=True, default='contacto@tallermecanico.cl', max_length=254),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_nombre',
            field=models.CharField(blank=True, default='Taller Mecánico Rápido', max_length=200),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_rut',
            field=models.CharField(blank=True, default='76.123.456-7', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_telefono',
            field=models.CharField(blank=True, default='+56 9 1234 5678', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
