# Generated by Django 4.2.24 on 2025-11-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_servicio_mano_obra_servicio_repuestos_servicio_total'),
        ('cotizaciones', '0007_alter_cotizacion_empresa_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='vehiculo.servicio'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='empresa_giro',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
