# Generated by Django 5.2.5 on 2025-11-04 21:33

import django.db.models.deletion
import vehiculo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('boleta', 'Boleta'), ('certificado', 'Certificado'), ('presupuesto', 'Presupuesto'), ('informe', 'Informe técnico'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('fecha_documento', models.DateField()),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos/%Y/%m/%d/')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='servicios.servicio')),
            ],
            options={
                'ordering': ['-fecha_documento'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True, validators=[vehiculo.models.validar_patente])),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('chasis', models.CharField(blank=True, max_length=50, null=True)),
                ('motor', models.CharField(blank=True, max_length=50, null=True)),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente')),
            ],
        ),
    ]
