# Generated by Django 5.2.5 on 2025-11-05 18:16

import django.db.models.deletion
import vehiculo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=10, unique=True, validators=[vehiculo.models.validar_patente])),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('chasis', models.CharField(blank=True, db_column='numero_chasis', max_length=50, null=True)),
                ('motor', models.CharField(blank=True, db_column='numero_motor', max_length=50, null=True)),
                ('kilometraje', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='clientes.cliente')),
            ],
        ),
    ]
