# Generated by Django 4.2.24 on 2025-10-04 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_tabajo_pendiente_id', models.IntegerField(blank=True, null=True, verbose_name='FK Orden Trabajo (Pendiente)')),
                ('tecnico_responsable_pendiente_id', models.IntegerField(blank=True, null=True, verbose_name='FK Técnico Responsable (Pendiente)')),
                ('fecha_servicio', models.DateTimeField()),
                ('descripcion_trabajo', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado_servicio', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='vehiculo.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=50)),
                ('fecha_documento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='vehiculo.servicio')),
            ],
        ),
    ]
