# Generated by Django 4.2.25 on 2025-10-06 02:10

from django.db import migrations, models
import vehiculo.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_servicio_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(help_text='Formato: AA1234 o ABCD12', max_length=10, unique=True, validators=[vehiculo.models.validar_patente_chilena]),
        ),
    ]
