# Generated by Django 4.2.25 on 2025-11-03 02:47

from django.db import migrations, models
import django.utils.timezone
import vehiculo.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_servicio_mano_obra_servicio_repuestos_servicio_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_documento', '-fecha_subida']},
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(default='', upload_to=vehiculo.models.documento_upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
