# Generated by Django 4.2.25 on 2025-11-03 03:04

from django.db import migrations, models
import vehiculo.models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_alter_documento_options_documento_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(upload_to=vehiculo.models.ruta_documento),
        ),
    ]
