# Generated by Django 4.2.25 on 2025-11-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('factura', 'Factura'), ('presupuesto', 'Presupuesto'), ('informe', 'Informe'), ('cotizacion', 'Cotización'), ('manual', 'Manual Técnico'), ('otro', 'Otro')], default='otro', max_length=50),
        ),
    ]
